### PR TITLE
Remove the reuse for UNIX stream DNS lookup.

### PR DESCRIPTION
**Pull request by madeye**
Our UNIX stream based DNS lookup doesn't support connection reuse.

### CODE REVIEW

**Comment by Mygod** [comment]
My compiler complains that this commit cannot be found: https://github.com/zonyitoo/tokio/commit/47b76a5a

**Comment by madeye** [comment]
I got the compilation error as well, you may have to rebase to an old commit.

**Comment by zonyitoo** [comment]
> My compiler complains that this commit cannot be found: [zonyitoo/tokio@47b76a5](https://github.com/zonyitoo/tokio/commit/47b76a5a)

Just ignore it. I will fix it until tokio's PR was merged.

**Review by Mygod — APPROVED** [review]
Can confirm this fixes everything. (I thought I was going to implement a DNS cache in shadowsocks-android for a moment so thank god!)

**Comment by zonyitoo** [comment]
The UNIX stream should report errors if the endpoint have been closed. Hmm.. Why it is the cause of shadowsocks/shadowsocks-android#2751 ?

**Review by zonyitoo — APPROVED** [review]
LGTM. But why?

**Comment by madeye** [comment]
Our android UNIX stream resolve doesn't support connection reuse yet.

I will use this PR to create a new release of shadowsocks-android as a hotfix. But for now, I think it's okay to keep it open for shadowsocks-rust.

**Comment by Mygod** [comment]
There is no reason to support connection reuse on local sockets since the delay is negligible. Currently, shadowsocks-android should close the socket (syscall `close`) after the response is written.

**Comment by zonyitoo** [comment]
Well, you are right about the cost of creating unix local stream is negligible. I am Ok with this PR, but I still cannot understand why it cause that issue.

Currently the implementation will open a new client if the connection have been lost due to `for _ in 0..self.retry_count`.

**Comment by Mygod** [comment]
Maybe we merge this and figure out the retry later? 😛

**Comment by zonyitoo** [comment]
I am worrying about if there are any issues in this connection management strategy, then it will also affects TCP and UDP DNS clients.

**Comment by zonyitoo** [comment]
Will shadowsocks-android implements connection reuse in the future?

**Comment by Mygod** [comment]
> There is no reason to support connection reuse on local sockets since the delay is negligible. Currently, shadowsocks-android should close the socket (syscall `close`) after the response is written.
> 
> EDIT: Holding a local socket open also wastes system resources methinks.

^

**Pull request merged**
