### PR TITLE
Allow passing in an optional plugin_arg

### PR DESCRIPTION
**Pull request by Mygod**
To be used by https://github.com/shadowsocks/shadowsocks-android/pull/2585.

@madeye Please review?

### CODE REVIEW

**Review by madeye — APPROVED** [review]
LGTM

**Comment by Mygod** [comment]
Oops misclicked request review. Ignore that. :rofl:

**Comment by zonyitoo** [comment]
Shouldn't it be an array of strings?

```
"plugin_args": ["-a", "xxx"]
```

**Comment by Mygod** [comment]
It's for internal use only and we only need one but sure feel free to change it.

**Comment by zonyitoo** [comment]
It works perfectly. I am going to merge it now.

**Comment by madeye** [comment]
A quick question, I got this kind of errors when building the master branch. Anything I missed here?

```
error[E0277]: the trait bound `std::net::SocketAddr: std::cmp::Ord` is not satisfied
   --> src/relay/udprelay/association.rs:795:62
    |
795 |         let resolved_address_cache = Arc::new(SyncMutex::new(LruCache::with_expiry_duration_and_capacity(
    |                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::cmp::Ord` is not implemented for `std::net::SocketAddr`
    |
    = note: required by `lru_time_cache::LruCache::<Key, Value>::with_expiry_duration_and_capacity`

error[E0599]: no method named `insert` found for struct `spin::mutex::MutexGuard<'_, lru_time_cache::LruCache<std::net::SocketAddr, relay::socks5::Address>>` in the current scope
   --> src/relay/udprelay/association.rs:925:47
    |
925 |                   resolved_address_cache.lock().insert(remote_addr, addr.clone());
    |                                                 ^^^^^^ method not found in `spin::mutex::MutexGuard<'_, lru_time_cache::LruCache<std::net::SocketAddr, relay::socks5::Address>>`
    |
    = note: the method `insert` exists but the following trait bounds were not satisfied:
            `std::net::SocketAddr: std::cmp::Ord`

error[E0599]: no method named `get` found for struct `spin::mutex::MutexGuard<'_, lru_time_cache::LruCache<std::net::SocketAddr, relay::socks5::Address>>` in the current scope
   --> src/relay/udprelay/association.rs:972:56
    |
972 |           let addr = match resolved_address_cache.lock().get(&remote_addr) {
    |                                                          ^^^ method not found in `spin::mutex::MutexGuard<'_, lru_time_cache::LruCache<std::net::SocketAddr, relay::socks5::Address>>`
    |
    = note: the method `get` exists but the following trait bounds were not satisfied:
            `std::net::SocketAddr: std::cmp::Ord`
```

**Comment by zonyitoo** [comment]
```
error[E0277]: the trait bound `std::net::SocketAddr: std::cmp::Ord` is not satisfied.
```

Upgrade your Rust :P

**Comment by madeye** [comment]
😅

**Pull request merged**
