### PR TITLE
Let DNS relay run on TCP as well

### PR DESCRIPTION
**Pull request by Mygod**
I tried integrating `trust-dns-server`, it turns out that using it will block the entire thread (it takes a `&Runtime` as input). To be fair, I suspect there is anything we can really use from trust-dns besides `trust-dns-proto`.

P.S. This TCP server closes connection for every query. This should not be an issue as the relay should run locally.

### CODE REVIEW

**Comment by zonyitoo** [comment]
Ah, so you are going to make dns-relay to be a DNS server?

**Comment by Mygod** [comment]
It has always been a DNS server, no? A server that only relays other's messages but a server nonetheless.

**Comment by Mygod** [comment]
It seems like build was failing due to missing fix in #245. Any other comments? @zonyitoo

**Comment by dev4u** [comment]
> It seems like build was failing due to missing fix in #245. Any other comments? @zonyitoo

@zonyitoo pls. review #248 . if there is no problem, pls merge to master.

**Comment by zonyitoo** [comment]
Merged. Please rebase with master.

**Comment by Mygod** [comment]
Looks like all checks have passed.

**Pull request merged**
