### PR TITLE
Connect UDP sockets

### LINKED ISSUE #263: Domain name is re-resolved for every UDP packet
This is *very* wasteful. Consider using `UdpSocket::connect` instead.

See also this for unexpected benefits: https://stackoverflow.com/a/51296247/2245107

### PR DESCRIPTION
**Pull request by Mygod**
Fixes #263. Untested.

### CODE REVIEW

**Comment by zonyitoo** [comment]
Looks awesome!

**Comment by zonyitoo** [comment]
Tests failed:

```
[ERROR shadowsocks::relay::udprelay::association] failed to send packet 127.0.0.1:59742 -> 127.0.0.1:9230, bypassed? false, error: Destination address required (os error 89)
```

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/pull/265/files#diff-7884f1e88e152d534accbe0bdc05abe6L329-L332

These `send_to` should also be replaced with `send`.

**Comment by zonyitoo** [comment]
I see. You have forgot this one: https://github.com/shadowsocks/shadowsocks-rust/pull/265/files#diff-7884f1e88e152d534accbe0bdc05abe6R154

**Comment by zonyitoo** [comment]
```rust
fn connect_remote(context: &Context, socket: &UdpSocket, svr_cfg: &ServerConfig) {
```

**Comment by zonyitoo** [comment]
@Mygod Come here and fix the test errors.

**Comment by Mygod** [comment]
What is `connect_remote`?

**Comment by zonyitoo** [comment]
> What is `connect_remote`?

I mean you can put [these codes](https://github.com/shadowsocks/shadowsocks-rust/pull/265/files#diff-7884f1e88e152d534accbe0bdc05abe6R80-R88) into a `connect_remote` and call it from `associate_proxied` and `associate_with_acl `

**Comment by Mygod** [comment]
Feel free to do it for me. :)

**Comment by zonyitoo** [comment]
I can't push to your branch.

**Comment by Mygod** [comment]
Well you can... I think I enabled "allow edits from maintainer".

**Comment by zonyitoo** [comment]
Already done locally. :P

**Comment by Mygod** [comment]
Rant: `Arc<Context>` is so hard to work with. We do not need to use this `Arc` if only `tokio` supports non `static spawns. Ugh.

**Comment by zonyitoo** [comment]
> we probably can just use a `&'a Context` pointer everywhere

I was thinking the same from years ago.

**Comment by Mygod** [comment]
How about always creating a `Context` with `'static`/nonmanaged lifetime? e.g. `Box::into_raw(Box::new(Context::new(...)))` (this gives `*mut Context` whose lifetime is unmanaged) This should be acceptable as we never deconstruct `Context` unless on exit/panic (even if it is used as a library).

Another alternative is to support graceful shutdown (support cancellation?) and [`tokio::task::scope`](https://github.com/tokio-rs/tokio/pull/2153).

**Comment by zonyitoo** [comment]
Using `unsafe` will always work.

**Comment by Mygod** [comment]
`Box::into_raw` is a safe method as rust runtime does not guarantee destruction of objects. (in fact the entire snippet there is safe)

On the other hand if we implement cancellation, we can probably wait for plugin process to exit as well since it does not involve panicking the tokio Runtime.

**Pull request merged**
