### PR TITLE
feat(mptcp): Basic implementation of Multipath-TCP

### PR DESCRIPTION
**Pull request by zonyitoo**
- Currently support macOS (Client Only) and Linux (> 5.19)
  - ref #1156

### CODE REVIEW

**Comment by dev4u** [comment]
请教一下，这玩意有什么用途吗？

**Comment by database64128** [comment]
The MPTCP folks seem to be pushing a lot lately. MPTCP support detection logic just got merged into the Go runtime: golang/go@59d7c69342edbf8943699394513fb9b8fb175d7e

**Comment by zonyitoo** [comment]
Some observation:

- Linux 5.19 (Ubuntu 22.10) doesn't support `TCP_KEEPIDLE` and `TCP_KEEPINTV` sockopts on accepted sockets. But it works for sockets after `connect`, interesting.

- macOS supports `AF_MULTIPATH` only for client sockets. `bind()` will return `EOPNOTSUPP` and `setsockopt` with `SO_REUSEADDR` will return `ENOPROTOOPT `.

```
socket(0x27, 0x1, 0x6)		 = 9 0
bind(0x9, 0x700005C74560, 0x10)		 = -1 102
```

**Comment by zonyitoo** [comment]
cc https://github.com/multipath-tcp/mptcp_net-next/issues/383

**Comment by wangyoucao577** [comment]
Hi, why does it require Linux > 5.19? It's MPTCPv1, which is available since Linux v5.6, right? https://github.com/multipath-tcp/mptcp_net-next/wiki#changelog

**Comment by zonyitoo** [comment]
Did you tried to run it under older version of Linux Kernel?

**Comment by wangyoucao577** [comment]
I haven't tried this app yet. But I have tried `mptcpize run -d iperf3` on Linux v5.15 (both client and server side), which worked well.

**Pull request merged**
