### PR TITLE
Update install instructions

### PR DESCRIPTION
**Pull request by Mygod**

### CODE REVIEW

**Comment by zonyitoo** [comment]
It doesn't need to set the default toolchain, just install any version of toolchains.

When you run `cargo`, it should automatically install the correct toolchain defined in `rust-toolchain`.

**Comment by Mygod** [comment]
Well. It didn't.

**Comment by zonyitoo** [comment]
No, it do.

image

**Comment by Mygod** [comment]
Yeah it would only if you are building it from repo, which is a different command from what this PR is about.

```sh
$ cargo install shadowsocks-rust --no-default-features --features "logging trust-dns server multi-threaded"
    Updating crates.io index
  Installing shadowsocks-rust v1.11.0
   Compiling libc v0.2.95
   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling autocfg v1.0.1
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.126
   Compiling serde v1.0.126
   Compiling memchr v2.4.0
   Compiling log v0.4.14
   Compiling proc-macro-hack v0.5.19
   Compiling futures-core v0.3.15
   Compiling futures-task v0.3.15
   Compiling futures-channel v0.3.15
   Compiling proc-macro-nested v0.1.7
   Compiling matches v0.1.8
   Compiling scopeguard v1.1.0
   Compiling futures-sink v0.3.15
   Compiling ppv-lite86 v0.2.10
   Compiling pin-project-lite v0.2.6
   Compiling tinyvec_macros v0.1.0
   Compiling bitflags v1.2.1
   Compiling smallvec v1.6.1
   Compiling slab v0.4.3
   Compiling linked-hash-map v0.5.4
   Compiling futures-io v0.3.15
   Compiling ryu v1.0.5
   Compiling once_cell v1.7.2
   Compiling pin-utils v0.1.0
   Compiling lazy_static v1.4.0
   Compiling percent-encoding v2.1.0
   Compiling ucd-trie v0.1.3
   Compiling cc v1.0.68
   Compiling async-trait v0.1.50
   Compiling crossbeam-utils v0.8.5
   Compiling unicode-segmentation v1.7.1
   Compiling bytes v1.0.1
   Compiling ipnet v2.3.0
   Compiling maplit v1.0.2
   Compiling match_cfg v0.1.0
   Compiling serde_json v1.0.64
   Compiling itoa v0.4.7
   Compiling quick-error v1.2.3
   Compiling anyhow v1.0.40
   Compiling data-encoding v2.3.2
   Compiling spin v0.5.2
   Compiling traitobject v0.1.0
   Compiling same-file v1.0.6
   Compiling untrusted v0.7.1
   Compiling bit-vec v0.6.3
   Compiling dtoa v0.4.8
   Compiling regex-syntax v0.6.25
   Compiling siphasher v0.3.5
   Compiling crypto2 v0.1.2
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto2-0.1.2/src/lib.rs:2:1
  |
2 | #![feature(stdsimd, llvm_asm)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `crypto2`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `shadowsocks-rust v1.11.0`, intermediate artifacts can be found at `/tmp/cargo-installdvXeea`

Caused by:
  build failed
```

**Comment by zonyitoo** [comment]
Ah.. I see.

**Comment by zonyitoo** [comment]
Can README.md read the data from `rust-toolchain`?

**Comment by Mygod** [comment]
🤷 lol

**Comment by zonyitoo** [comment]
Why not just `rustup default nightly`? It should work for most cases.

**Comment by Mygod** [comment]
Sure?

**Comment by zonyitoo** [comment]
Nevermind, merge it first.

**Comment by IceCodeNew** [comment]
> Sure?

Sure. I build ss-rust twice a day with the latest rust nightly toolchain.
As long as I could tell, there is no error caused by the discrepancy between the project preferred nightly release and the latest version of the nightly toolchain.

**Comment by Mygod** [comment]
> Can README.md read the data from `rust-toolchain`?

You can add a human pointer, like [this](https://github.com/shadowsocks/shadowsocks-rust/blob/master/rust-toolchain). (Oh I guess that is technically called a hyperlink.)

**Comment by zonyitoo** [comment]
> > Sure?
> 
> Sure. I build ss-rust twice a day with the latest rust nightly toolchain.
> As long as I could tell, there is no error caused by the discrepancy between the project preferred nightly release and the latest version of the nightly toolchain.

Haha. But some nightly releases do have bugs, some of them could be fatal but unsound.

**Pull request merged**
