### PR TITLE
chore(k8s): change default image to ghcr latest

### PR DESCRIPTION
**Pull request by longkai**
Sorry for the last PR. I forgot to change the default docker image after local testing.

### CODE REVIEW

**Comment by zonyitoo** [comment]
And you should delete the `nameserver` key in the configuration file which is not recognized in this project.

**Comment by longkai** [comment]
Done

**Comment by database64128** [comment]
Might as well remove the `timeout` field and change the listening address to `::`. Unlike Go, Rust programs generally don't interpret `0.0.0.0` as `::`.

**Comment by zonyitoo** [comment]
Agree. Listening on `::` with dual-stack IPv6 support should cover more users' use cases.

**Comment by longkai** [comment]
Those fields comes from libev and I've done that.

BTW, I still see some timeout and 0.0.0.0 server address in the project, but it's better with another dedicated PR.

**Pull request merged**
