### PR TITLE
Update debian/changelog (v1.9.1)

### PR DESCRIPTION
**Pull request by kimw**

### CODE REVIEW

**Comment by zonyitoo** [comment]
How to genereate this file from release?

**Comment by kimw** [comment]
It's "generated" by my bare hands 🥲

---

1. Copy change log content from release info.
2. Catch date time from git log by command such as `git show --date=rfc v1.9.1`

Barely, huh?

**Comment by kimw** [comment]
@zonyitoo how do you make the release? Maybe we can,

1. Write release info into `debian/changelog`
2. Run a script to release to GitHub with the information from `debian/changelog`

How's about it?

**Comment by zonyitoo** [comment]
Currently there is another PR for building RPM #436 . So .. maybe we should have a common `CHANGELOG` file and then generates it to different targets.

**Pull request merged**
