### PR TITLE
CLAP: Simple parameter configuration replaced with macro expressions

### PR DESCRIPTION
**Pull request by Stzx**
;)

### CODE REVIEW

**Comment by zonyitoo** [comment]
Superb!

**Comment by Stzx** [comment]
😂

I seem to submit the commit information wrong, and the submission becomes `zx <zxown.v@foxmail.com>`

**Comment by zonyitoo** [comment]
You need to modify the author?

**Comment by Stzx** [comment]
If possible, change to `Stzx <silence.m@hotmail.com>`.

To be honest, force push is not a good idea 😰.

I am sorry for causing this problem.

**Comment by zonyitoo** [comment]
I can revert changes in this PR. And then you can make a new PR.

**Comment by Stzx** [comment]
Ok.

**Comment by zonyitoo** [comment]
Now, you can make a new PR.

**Pull request merged**
