### PR TITLE
macOS fix netmask API

### PR DESCRIPTION
**Pull request by BranLiang**
related https://github.com/meh/rust-tun/pull/56

Not meant to merge this patch directly, just want to raise the netmask problem from dependency `rust-tun`. Seems that package is not actively maintained.

### CODE REVIEW

**Comment by zonyitoo** [comment]
> Seems that package is not actively maintained.

Yes, it’s true.

**Comment by BranLiang** [comment]
Any ideas on how to fix the problem?

**Comment by zonyitoo** [comment]
You could send email to the author.

**Comment by BranLiang** [comment]
@zonyitoo package is updated 😄 please see if this PR could be merged.

**Pull request merged**
