### PR TITLE
Add `ProxySocket::as_raw_fd`

### PR DESCRIPTION
**Pull request by dlon**
I need this in order to pass the file descriptor to [`VpnService.protect`](https://developer.android.com/reference/android/net/VpnService#protect(int)).

### CODE REVIEW

**Comment by dlon** [comment]
I've now discovered `vpn_protect_path`! However, in our case, it makes more sense to obtain the fd directly than to pass it over a UDS, and I'm sure there are other use cases as well.

**Comment by dlon** [comment]
@zonyitoo Thank you. Can you please also make a release for this?

**Comment by zonyitoo** [comment]
I am quite busy these days. I will try to make it published ASAP.

**Comment by zonyitoo** [comment]
Released `shadowsocks` v1.20.3.

**Pull request merged**
