### PR TITLE
Added configs for snap daemons

### PR DESCRIPTION
**Pull request by fertkir**
Currently if you run `snap start shadowsocks-rust.ssserver-daemon` it will fail because of the missing config.

This patch adds paths to config files. All a user needs to do is to add desired local/server configs to $SNAP_COMMON directory.

Still there's a problem, that only one `sslocal`/`ssserver` daemon instance is allowed.
With `ssserver` you can work around this by runing multiple servers in one process (shadowsocks config allows it).
But with `sslocal` this is, alas, impossible.

### CODE REVIEW

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/0c4f9da320e414be59aadf764f3d586ed4df59e2/src/config.rs#L59-L66

`/etc/shadowsocks-rust/config.json` is in the default path.

**Comment by fertkir** [comment]
I don't think that having one config file for both `ssserver` and `sslocal` is very usable, since same config fields mean different things for server and local. AFAIU, server and local need separate configs.

**Comment by zonyitoo** [comment]
Why would you run `sslocal` and `ssserver` simotanously on the same machine?

On the other hand, add these `local.json` and `server.json` into `src/config.rs`.

**Comment by fertkir** [comment]
Added, please review

**Comment by fertkir** [comment]
Also, do you know any way to run multiple instances of  `sslocal` snap daemon?

**Comment by zonyitoo** [comment]
I don't know. I run my own services with handwriting systemd service files.

**Comment by fertkir** [comment]
Me too. But when running snaps with handwritten system service, `journalctl` doesn't show the logs.

**Comment by zonyitoo** [comment]
Hmm, shouldn't we also support `config.json`?

**Comment by fertkir** [comment]
It is used if `server.json`/`client.json` is not provided:
``
 let config_files = vec![config_file, "config.json"];
`

**Pull request merged**
